export const ridesDumbs = [
  {
    passengerId: 1,
    driverId: 1,
    startLocationId: 12,
    endLocationId: 11,
    status: 'finished',
  },
  {
    passengerId: 2,
    driverId: 3,
    startLocationId: 11,
    endLocationId: 12,
    status: 'finished',
  },
  {
    passengerId: 2,
    driverId: 4,
    startLocationId: 13,
    endLocationId: 13,
    status: 'finished',
  },
  {
    passengerId: 4,
    driverId: 6,
    startLocationId: 14,
    endLocationId: 14,
    status: 'finished',
  },
  {
    passengerId: 2,
    driverId: 4,
    startLocationId: 15,
    endLocationId: 15,
    status: 'finished',
  },
  {
    passengerId: 5,
    driverId: 3,
    startLocationId: 16,
    endLocationId: 16,
    status: 'finished',
  },
  {
    passengerId: 6,
    driverId: 7,
    startLocationId: 17,
    endLocationId: 17,
    status: 'active',
  },
  {
    passengerId: 7,
    driverId: 8,
    startLocationId: 18,
    endLocationId: 18,
    status: 'active',
  },
  {
    passengerId: 8,
    driverId: 9,
    startLocationId: 19,
    endLocationId: 19,
    status: 'active',
  },
  {
    passengerId: 9,
    driverId: 10,
    startLocationId: 20,
    endLocationId: 20,
    status: 'active',
  },
];
